# Generated by Django 6.0.3 on 2026-04-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='GenericItemName', max_length=500)),
                ('department', models.CharField(choices=[('Command', 'command'), ('Engineering', 'engineering'), ('Tactical/Security', 'tacticalsecurity'), ('Science', 'science'), ('Operations/Systems', 'operationssystems'), ('LifeSupport/Environmental', 'lifesupportenvironmental'), ('Medical', 'medical'), ('Holographic/Recreation', 'holographicrecreation'), ('AuxiliaryAndSpecialSystems', 'auxiliaryspecialsystems')], max_length=50)),
            ],
        ),
    ]
