# Generated by Django 6.0.3 on 2026-04-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='department',
            field=models.CharField(choices=[('Command', 'Command'), ('Engineering', 'Engineering'), ('Tactical/Security', 'Tactical / Security'), ('Science', 'Science'), ('Operations/Systems', 'Operations/Systems'), ('LifeSupport/Environmental', 'Life Support / Environmental'), ('Medical', 'Medical'), ('Holographic/Recreation', 'Holographic / Recreation'), ('AuxiliaryAndSpecialSystems', 'Auxiliary / Special Systems')], max_length=50),
        ),
    ]
