# Generated by Django 6.0.3 on 2026-04-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_is_working_alter_inventory_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='InventoryItem',
        ),
    ]
