# Generated by Django 6.0.3 on 2026-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_inventory_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='descriptions',
            field=models.CharField(default='GenericDescription', max_length=500),
        ),
    ]
