# Generated by Django 6.0.3 on 2026-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='descriptions',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
