# Generated by Django 6.0.3 on 2026-04-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phasers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phaser_is_working', models.BooleanField(default=True)),
                ('direction_fireing', models.CharField(choices=[('U', 'up'), ('D', 'down'), ('L', 'left'), ('R', 'right')], default='R', max_length=1)),
            ],
        ),
    ]
