# Generated by Django 6.0.3 on 2026-05-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasers',
            name='direction_fireing',
            field=models.CharField(choices=[('U', 'Aimed Up'), ('D', 'Aimed Down'), ('L', 'Aimed Left'), ('R', 'Aimed Right')], default='R', max_length=1),
        ),
    ]
